spring:
  liquibase:
    change-log: classpath:/db/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/task