spring:
  liquibase:
    change-log: classpath:/db/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: vdvdgjdbgnxflu
    password: 2d40500e97cd58bafc91737c0660bce8fabcf94fdd95cade386344fb61cd2e34
    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/d77mb372f5smbn

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT:8080}